import * as datadog from "@vincentgna/cdk8s-datadog";
import { Construct } from "constructs";
import { DatadogMonitorProps } from "./DatadogMonitorProps.generated";

export class DatadogMonitor extends Construct {
  constructor(scope: Construct, id: string, props: DatadogMonitorProps) {
    super(scope, id);
    new datadog.DatadogMonitor(this, id, {
      // metadata is generated by Chart
      // https://github.com/cdk8s-team/cdk8s-core/blob/v2.67.2/src/chart.ts#L106-L131
      spec: props,
    });
  }
}
