// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
export type AuditAlertType = "audit alert";
export type EventAlertType = "event alert";
export type EventV2AlertType = "event-v2 alert";
export type LogAlertType = "log alert";
export type MetricAlertType = "metric alert";
export type ProcessAlertType = "process alert";
export type QueryAlertType = "query alert";
export type RumAlertType = "rum alert";
export type ServiceCheckType = "service check";
export type SloAlertType = "slo alert";
export type TraceAnalyticsAlertType = "trace-analytics alert";